force-app/main/default/objects/Vacations__mdt/Vacations__mdt.object-meta.xml
<CustomObject>
    <label>Vacation</label>
    <pluralLabel>Vacations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Vacations__mdt/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SplitVacationList.cls
public class SplitVacationList {
    @auraenabled
    Public static Map<string,string> splitVacationList(){
        /*string ListofVacation=label.Vacation_Types;
list<string>vacations = ListofVacation.split(',');
return vacations;
*/
        List<Vacations__mdt> VacTypes = [select Type_name__C,MasterLabel,developerName from Vacations__mdt];
        Map <string,string> Option =new map<string,string>();
        for (vacations__mdt VType:VacTypes)
        {
            Option.put(Vtype.developerName,VType.Type_name__C);
            
        }
        return option;
        
    }
}