force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetProductDetails_IsTest.cls
@IsTest
public class GetProductDetails_IsTest {
    @testSetup
    public static void Datasetup(){
       account acc = new Account(name='karim12123');
        insert acc;
    }
    @isTest
    public static void test_getproductdetails(){
        test.startTest();   
        account acct = new account();
        acct.name = 'n26';

        contact cont = new contact();
        cont.FirstName='karim';
        cont.lastname='Ahmed';
        cont.Home_Country__c='FR';
        cont.UUID__c='1234567';
        cont.Product__c='Metal';
        cont.AccountId=acct.id;   
        Insert cont;
        
        contact cont2 = new contact();
        cont2.FirstName='karim';
        cont2.lastname='Ahmed';
        cont2.Home_Country__c='FR';
        cont2.UUID__c='12345674';
        cont2.AccountId=acct.id;   
        Insert cont2;
        
        case case1 = new case();
        case1.origin = 'phone';
        case1.AccountId=acct.id;
        case1.ContactId=cont.id;
        Insert case1;
        
        case case2 = new case();
        case2.origin = 'phone';
        case2.AccountId=acct.id;
        case2.ContactId=cont2.id;
        Insert case2;
        
        test.stopTest();
        system.assertEquals(getproductdetails.getProductDetails(case1.contactId, ''), getproductdetails.getProductDetails('', cont.uuid__c));
        system.AssertEquals(1,getproductdetails.getProductDetails(case1.contactId, '').size());
        system.AssertEquals(1,getproductdetails.getProductDetails('', cont.uuid__c).size());
        system.assertequals('NA',getproductdetails.getProductDetails(case2.contactId, '')[0].masterlabel);
        system.assertEquals(getproductdetails.getProductDetails(case2.contactId, ''), getproductdetails.getProductDetails('', cont2.uuid__c));
        
    }
    
}