force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26__mdt/N26__mdt.object-meta.xml
<CustomObject>
    <label>N26</label>
    <pluralLabel>n26</pluralLabel>
</CustomObject>

force-app/main/default/objects/N26__mdt/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26__mdt/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26__mdt/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetProductDetails.cls
public class GetProductDetails {
    @AuraEnabled
    public static List<n26__mdt> getProductDetails(string ContactID,string uuid){
        contact Contact = new contact();
        //method called from the caseContactComp LWC
        if(string.isBlank(uuid) && !string.isBlank(ContactID)){
            contact = [SELECT id,product__c, home_country__c, Email FROM Contact WHERE Id= :contactId];
        }
        //method called from the contact_endpoint class
        else if(!string.isBlank(uuid) && string.isBlank(ContactID)){
            contact = [SELECT id,product__c, home_country__c, Email FROM Contact WHERE uuid__c= :uuid];
        }
        //Get details from the custom metadatatype by country and product
        list<n26__mdt> prodList = new list<n26__mdt>();
        if(contact <> null && contact.product__C <> null && contact.Home_Country__c <> null){
            prodList = database.query('select masterlabel,category__c,ATM_Fee_in_other_currencies__c ,Card_Replacement_Cost__c ,Cost_per_Calendar_Month__c from n26__mdt where category__c =\''+contact.product__c+'\' and masterlabel like \'%'+contact.Home_Country__c+'%\' order by masterlabel');
        }else{
            //fill return values with No Data if no records
            n26__mdt emptyRecord = new n26__mdt();
            emptyRecord.masterlabel ='NA';
            emptyRecord.category__c = 'NO DATA';
            emptyRecord.Card_Replacement_Cost__c='NO DATA';
            emptyRecord.ATM_Fee_in_other_currencies__c='NO DATA';
            emptyRecord.Cost_per_Calendar_Month__c='NO DATA';
            prodList.add(emptyrecord);
        }
        
        
        
        return prodlist;
    }
    
}